export default {
  AMOUNT_DEFAULT: 0,
  SYMBOL_USDT_TRC20: 'USDT-TRC20',
  SYMBOL_USDT_ERC20: 'USDT-ERC20',
  TRANSACTION_STATUS_PENDING: 0,
  TRANSACTION_STATUS_SUCCESS: 1,
  TRANSACTION_STATUS_CANCELLED: 2,
  TRANSACTION_STATUS_PROCESSING: 3,
  TRANSACTION_TYPE_DEPOSIT: 0,
  TRANSACTION_TYPE_TRANSFER: 1,
  TRANSACTION_TYPE_WITHDRAW: 2,
  TRANSACTION_TYPE_BUY_SPONSOR: 3,
  TRANSACTION_TYPE_TEMP_DEPOSIT: 4,
};
